// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: eta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_eta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_eta_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinate) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type GenerateETARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        *Coordinate `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To          *Coordinate `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TransportId uint32      `protobuf:"varint,3,opt,name=transportId,proto3" json:"transportId,omitempty"`
}

func (x *GenerateETARequest) Reset() {
	*x = GenerateETARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateETARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateETARequest) ProtoMessage() {}

func (x *GenerateETARequest) ProtoReflect() protoreflect.Message {
	mi := &file_eta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateETARequest.ProtoReflect.Descriptor instead.
func (*GenerateETARequest) Descriptor() ([]byte, []int) {
	return file_eta_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateETARequest) GetFrom() *Coordinate {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GenerateETARequest) GetTo() *Coordinate {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GenerateETARequest) GetTransportId() uint32 {
	if x != nil {
		return x.TransportId
	}
	return 0
}

type GenerateETAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance float32 `protobuf:"fixed32,1,opt,name=distance,proto3" json:"distance,omitempty"` // км
	Duration uint32  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`  //минут
}

func (x *GenerateETAResponse) Reset() {
	*x = GenerateETAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateETAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateETAResponse) ProtoMessage() {}

func (x *GenerateETAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateETAResponse.ProtoReflect.Descriptor instead.
func (*GenerateETAResponse) Descriptor() ([]byte, []int) {
	return file_eta_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateETAResponse) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GenerateETAResponse) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_eta_proto protoreflect.FileDescriptor

var file_eta_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0a, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x22, 0x74, 0x0a,
	0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x54, 0x41, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45,
	0x54, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x32, 0x48, 0x0a, 0x0a, 0x45, 0x54, 0x41, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x54, 0x41, 0x12,
	0x13, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x54, 0x41, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45,
	0x54, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eta_proto_rawDescOnce sync.Once
	file_eta_proto_rawDescData = file_eta_proto_rawDesc
)

func file_eta_proto_rawDescGZIP() []byte {
	file_eta_proto_rawDescOnce.Do(func() {
		file_eta_proto_rawDescData = protoimpl.X.CompressGZIP(file_eta_proto_rawDescData)
	})
	return file_eta_proto_rawDescData
}

var file_eta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eta_proto_goTypes = []interface{}{
	(*Coordinate)(nil),          // 0: Coordinate
	(*GenerateETARequest)(nil),  // 1: GenerateETARequest
	(*GenerateETAResponse)(nil), // 2: GenerateETAResponse
}
var file_eta_proto_depIdxs = []int32{
	0, // 0: GenerateETARequest.from:type_name -> Coordinate
	0, // 1: GenerateETARequest.to:type_name -> Coordinate
	1, // 2: ETAService.generateETA:input_type -> GenerateETARequest
	2, // 3: ETAService.generateETA:output_type -> GenerateETAResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eta_proto_init() }
func file_eta_proto_init() {
	if File_eta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateETARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateETAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eta_proto_goTypes,
		DependencyIndexes: file_eta_proto_depIdxs,
		MessageInfos:      file_eta_proto_msgTypes,
	}.Build()
	File_eta_proto = out.File
	file_eta_proto_rawDesc = nil
	file_eta_proto_goTypes = nil
	file_eta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc_controller package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ETAServiceClient is the client API for ETAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ETAServiceClient interface {
	GenerateETA(ctx context.Context, in *GenerateETARequest, opts ...grpc.CallOption) (*GenerateETAResponse, error)
}

type eTAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewETAServiceClient(cc grpc.ClientConnInterface) ETAServiceClient {
	return &eTAServiceClient{cc}
}

func (c *eTAServiceClient) GenerateETA(ctx context.Context, in *GenerateETARequest, opts ...grpc.CallOption) (*GenerateETAResponse, error) {
	out := new(GenerateETAResponse)
	err := c.cc.Invoke(ctx, "/ETAService/generateETA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ETAServiceServer is the server API for ETAService service.
type ETAServiceServer interface {
	GenerateETA(context.Context, *GenerateETARequest) (*GenerateETAResponse, error)
}

// UnimplementedETAServiceServer can be embedded to have forward compatible implementations.
type UnimplementedETAServiceServer struct {
}

func (*UnimplementedETAServiceServer) GenerateETA(context.Context, *GenerateETARequest) (*GenerateETAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateETA not implemented")
}

func RegisterETAServiceServer(s *grpc.Server, srv ETAServiceServer) {
	s.RegisterService(&_ETAService_serviceDesc, srv)
}

func _ETAService_GenerateETA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateETARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETAServiceServer).GenerateETA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ETAService/GenerateETA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETAServiceServer).GenerateETA(ctx, req.(*GenerateETARequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ETAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ETAService",
	HandlerType: (*ETAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generateETA",
			Handler:    _ETAService_GenerateETA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eta.proto",
}
