// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: weight.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DimensionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight float32 `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Length float32 `protobuf:"fixed32,2,opt,name=length,proto3" json:"length,omitempty"`
	Width  float32 `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *DimensionsRequest) Reset() {
	*x = DimensionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DimensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionsRequest) ProtoMessage() {}

func (x *DimensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionsRequest.ProtoReflect.Descriptor instead.
func (*DimensionsRequest) Descriptor() ([]byte, []int) {
	return file_weight_proto_rawDescGZIP(), []int{0}
}

func (x *DimensionsRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DimensionsRequest) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DimensionsRequest) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DimensionsRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type DimensionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransportId uint32  `protobuf:"varint,1,opt,name=transportId,proto3" json:"transportId,omitempty"`
	Volume      float32 `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
	From        uint32  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To          uint32  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *DimensionsResponse) Reset() {
	*x = DimensionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DimensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionsResponse) ProtoMessage() {}

func (x *DimensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionsResponse.ProtoReflect.Descriptor instead.
func (*DimensionsResponse) Descriptor() ([]byte, []int) {
	return file_weight_proto_rawDescGZIP(), []int{1}
}

func (x *DimensionsResponse) GetTransportId() uint32 {
	if x != nil {
		return x.TransportId
	}
	return 0
}

func (x *DimensionsResponse) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *DimensionsResponse) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *DimensionsResponse) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_weight_proto protoreflect.FileDescriptor

var file_weight_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71,
	0x0a, 0x11, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x72, 0x0a, 0x12, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x74, 0x6f, 0x32, 0x4c, 0x0a, 0x0d, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x2e, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x44,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weight_proto_rawDescOnce sync.Once
	file_weight_proto_rawDescData = file_weight_proto_rawDesc
)

func file_weight_proto_rawDescGZIP() []byte {
	file_weight_proto_rawDescOnce.Do(func() {
		file_weight_proto_rawDescData = protoimpl.X.CompressGZIP(file_weight_proto_rawDescData)
	})
	return file_weight_proto_rawDescData
}

var file_weight_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_weight_proto_goTypes = []interface{}{
	(*DimensionsRequest)(nil),  // 0: DimensionsRequest
	(*DimensionsResponse)(nil), // 1: DimensionsResponse
}
var file_weight_proto_depIdxs = []int32{
	0, // 0: WeightService.generateWeight:input_type -> DimensionsRequest
	1, // 1: WeightService.generateWeight:output_type -> DimensionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weight_proto_init() }
func file_weight_proto_init() {
	if File_weight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_weight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DimensionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weight_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DimensionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weight_proto_goTypes,
		DependencyIndexes: file_weight_proto_depIdxs,
		MessageInfos:      file_weight_proto_msgTypes,
	}.Build()
	File_weight_proto = out.File
	file_weight_proto_rawDesc = nil
	file_weight_proto_goTypes = nil
	file_weight_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WeightServiceClient is the client API for WeightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeightServiceClient interface {
	GenerateWeight(ctx context.Context, in *DimensionsRequest, opts ...grpc.CallOption) (*DimensionsResponse, error)
}

type weightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightServiceClient(cc grpc.ClientConnInterface) WeightServiceClient {
	return &weightServiceClient{cc}
}

func (c *weightServiceClient) GenerateWeight(ctx context.Context, in *DimensionsRequest, opts ...grpc.CallOption) (*DimensionsResponse, error) {
	out := new(DimensionsResponse)
	err := c.cc.Invoke(ctx, "/WeightService/generateWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightServiceServer is the server API for WeightService service.
type WeightServiceServer interface {
	GenerateWeight(context.Context, *DimensionsRequest) (*DimensionsResponse, error)
}

// UnimplementedWeightServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWeightServiceServer struct {
}

func (*UnimplementedWeightServiceServer) GenerateWeight(context.Context, *DimensionsRequest) (*DimensionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateWeight not implemented")
}

func RegisterWeightServiceServer(s *grpc.Server, srv WeightServiceServer) {
	s.RegisterService(&_WeightService_serviceDesc, srv)
}

func _WeightService_GenerateWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DimensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightServiceServer).GenerateWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WeightService/GenerateWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightServiceServer).GenerateWeight(ctx, req.(*DimensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeightService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WeightService",
	HandlerType: (*WeightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generateWeight",
			Handler:    _WeightService_GenerateWeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weight.proto",
}
